# Valid types: memory, textfiles, binaryfiles
repository = textfiles

# Text file config
students = students.txt
disciplines = disciplines.txt
grades = grades.txt

# Binary file config (switch 'repository' to 'binaryfiles' to use these)
# students = students.bin
# disciplines = disciplines.bin
# grades = grades.bin